HOSTS:
  ubuntu-12.04-amd64-digital-ocean:
    roles:
      - master
    flavor: '512MB'
    platform: ubuntu-12.04-amd64
    image_id: 6374128
    region: 'London 1'
    hypervisor : digital_ocean
CONFIG:
  type: git
